### ISSUE TITLE
Log out text not responsive in app main

### ISSUE THREAD

**Issue by aro** [enonic/xp-apps#106]
The width for the "Log out" in the log-out button in the Home app is hard-coded, and the text in other languages is cut, even though there is enough space.

Adjust the styling so it's a bit more responsive. And verify it with the languages supported.
The problem is visible setting browser language to Spanish.

![screen shot 2017-10-04 at 10 48 04](https://user-images.githubusercontent.com/430739/31167414-4101654c-a8f2-11e7-905d-3da13e11c228.png)

**Comment by jsi** [comment]
If this is fixed really quickly and in a simple way (maybe with CSS only), we can include it in 6.12, but it is not important, and if #94 is finished first, I will go ahead with the release and take this out of the 6.12.0 milestone.
