### ISSUE TITLE
Users App - second tabItem is getting not  clickable, when the first tab was closed after the deleting of user

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#112]
1. double click on an user and open it
2. do the same with the next user(two wizards are opened)
3. click on AppHome button and go to the grid
4. select the user that  was opened by the second and remove it
![step1](https://user-images.githubusercontent.com/3728712/31225176-80b5ec5c-a9d9-11e7-9c39-b5e21eb938e4.png)

5. click on the second tab, try to navigate to wizard
BUG: wizard is not opened, when the tab has been clicked

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #79](https://github.com/enonic/lib-admin-ui/issues/79) via [**ZenHub**](https://www.zenhub.com/)
