### ISSUE TITLE
Site Configurator Dialog - not correct message appears when the 'Posts folder' was deleted in the grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#131]
1. Open site configurator dialog and select a folder in the 'Posts folder' selector
2. Go to  the grid and remove the folder
3. Open  ' site configurator dialog'

Issue:
![mess](https://user-images.githubusercontent.com/3728712/31488687-2e35846a-af47-11e7-89ee-0e43be306cdd.png)

**Comment by alansemenov** [comment]
@sgauruseu why is it incorrect? this is standard message that we show when opening content that references another content that was deleted.

**Comment by sgauruseu** [comment]
@ase I thought that id is not good for the message , but probably the name is not available at this moment

**Comment by alansemenov** [comment]
Yes, we can't use name - the only thing we have left is **id** pointing to the deleted content.
