### ISSUE TITLE
Title of the New action changes on expand/collapse of a node in the Users app

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#135]
1. Open the Users app
2. Click on the "Roles" folder. "New..." changes to "New Role" in the toolbar.
3. Expand the "Roles" folder
4. Collapse the "Roles" folder. "New Role" changed to "New..."

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #106](https://github.com/enonic/lib-admin-ui/issues/106) via [**ZenHub**](https://www.zenhub.com/)
