### ISSUE TITLE
Users app - wizard tab is not closed, when the item has been deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#141]
1.  Open an User or Role
2. do not close the wizard but go to the grid and delete the User
BUG: the user is deleted, but tab still present on the toolbar
Issue with refreshing of the grid can be cause of the bug 

![tabs](https://user-images.githubusercontent.com/3728712/31600246-678748d8-b25e-11e7-953c-d6f493385f8a.png)

**Comment by pmi** [comment]
Can't reproduce this one as well
