### ISSUE TITLE
Users App - Changes to the grid made in another browser window are not synchronized

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#15]
1. open Users in two first browser-windows
2.  select the first browser-window and add a new UserStore
3. switch to the second browser-window
BUG new User store is not present in the  grid

**Comment by alansemenov** [comment]
Should follow the same principle as updates in the Content grid

**Comment by alansemenov** [comment]
It works fine when existing users are deleted or modified. But when I create a new user, it won't appear in the grid, even when I create it in the same browser window. I now have to refresh the grid manually to see the new user.
