### ISSUE TITLE
UserWizard - incorect saving of roles, when the roles were filtered and added

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#153]
1. Open user-wizard
2. Type name, e-mail, password
3. type in options filter(roles): 'cms.cm.app' and click on the filtered row
4. type in options filter(roles): 'cms.admin'  and click onthe filterd row
5. Press on the Save button

BUG: one role disappears, when the save button has been pressed

![roles](https://user-images.githubusercontent.com/3728712/31672366-0e1d8a34-b365-11e7-8aed-ccfdfee1d51d.png)

**Comment by jsi** [comment]
This bug is not in 6.12.0, so it has been introduced while bugfixing for 6.12.1.
It must be fixed before 6.12.1 release.

**Comment by alansemenov** [comment]
@sgauruseu I didn't manage to reproduce it locally (tried in Chrome and FF) and Users app on QA is giving errors, so I couldn't test it there. 

@jsi can you try to reproduce it?

**Comment by alansemenov** [comment]
This one and #154 were caused by invalid RC1-distro.
