### ISSUE TITLE
User Wizard - filtered options does not return to the initial state

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#154]
1. Open user-wizard
2. Type 'Content Manager Administrator' in options filter for Roles
3. clear(remove by backspace) the text in the input
BUG: input is empty but options is not returned to the initial state

![empty](https://user-images.githubusercontent.com/3728712/31672767-1733f4a4-b366-11e7-86e3-449c02814cca.png)

 

'

**Comment by alansemenov** [comment]
This one and #153 were caused by invalid RC1-distro.
