### ISSUE TITLE
User Store wizard - No call to fetch ID providers

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#157]
1. Open the wizard for a new user store
2. Expand the ID provider dropdown - the list is empty (there should be at least "Standard ID provider" there)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #113](https://github.com/enonic/lib-admin-ui/issues/113) via [**ZenHub**](https://www.zenhub.com/)
