### ISSUE TITLE
User Wizard - Assigned roles disappear after assigning a group and saving

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#158]
1. Make sure you have at least one user group in the Users app
2. Open a user that has roles assigned to him, or assign some to an existing user
3. Assign a group to the user (so that he has both groups and roles assigned)
4. Save

After the save the list of roles disappears, only the group remains. If you refresh the page, both the group and the roles will appear, so data is correct.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #110](https://github.com/enonic/lib-admin-ui/issues/110) via [**ZenHub**](https://www.zenhub.com/)
