### ISSUE TITLE
Save Before Close dialog appears on every close when using ID Provider with config

### ISSUE THREAD

**Issue by jsi** [enonic/xp-apps#164]
... and possibly other ID Providers.

1. Create a User Store with the Simple ID Provider and save it.
2. Close it: Save Before Close dialog appears.
3. Click Yes.  Dialog comes back again and again on Yes.
4. Clock No. User Store is saved with all changes.

This does not happen with the Standard ID Provider.
The bug is present in 6.12.0 and 6.12.1.  I have not tested 6.13....

**Comment by jsi** [comment]
@GlennRicaud thinks this is a bug in User App that appears for configurable ID Providers.
It does not appear for the Standard ID Provider, but will happen for all others, as they may be configured.  -  It is just loud thinking, but when this issue is started, it might be something to look into and maybe ask Glenn about. 😊

**Comment by GlennRicaud** [comment]
My guess is that it is starting from 6.12, because of all the app users refactoring.
I guess there is a bug there

**Comment by alansemenov** [comment]
This problem should fix itself after proper solution of https://github.com/enonic/xp/issues/5711. @gri please add comments/instructions in that task.

**Comment by GlennRicaud** [comment]
We rollbacked to the rest api for the 4 userstore requests:
 We will do it properly with the authLib.getUserStore that you are already working on in 6.13
