### ISSUE TITLE
Fix linting errors and add missing build steps

### ISSUE THREAD

**Issue by edloidas** [enonic/xp-apps#169]
Fix the problems that occurred after the feature #11 implementation and related issues:
* Exclude third party libs from linting;
* Fix Autoprefixer usage in `app-main` and `app-contentstudio`.

__Additional:__
* [x] Create a shareable browserslist config.
__Done__: [browserslist-config-enonic](https://www.npmjs.com/package/browserslist-config-enonic)

**Comment by alansemenov** [comment]
Nice job!
