### ISSUE TITLE
Users app - GraphQL Userstore requests rollback

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp-apps#185]
Support issue: https://enonic.zendesk.com/agent/tickets/2179
We cannot create/update/display a userstore with an ID Provider config.

After analysis:
* Some code is using the Rest API and some code is using the GraphQL endpoint
* The part to handle ID Provider config is just not done at all (A TODO is present in the code). And it would require some work to make it work the way it is intended to.

Solution: The old REST API requests classes are still available (and still used in some cases) so let's rollback to this classes.

For 6.13: We should decide if we want to pursue with GraphQL or rollback. Will create a task about it

**Comment by GlennRicaud** [comment]
Was actually discovered there: https://github.com/enonic/xp-apps/issues/164

**Comment by sigdestad** [comment]
Ups.. So are your saying this feature is completely defective at the moment?

**Comment by GlennRicaud** [comment]
Yes. The ID Provider config is not retrieved at all (would require some work) and the update is not correct (wrong structure).
Since it was a critical ticket, I thought it was better to rollback to the classic rest API for user stores and fix it correctly in 6.13.
