### ISSUE TITLE
Add new gradle tasks for running js-ui-tests on a local machine

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#187]
+ run the configuration and check allure reports

**Comment by jsi** [comment]
I am setting this back to "Review".  I would like to check this and make sure I can run it on Mac as well.  This is an important step to make sure the project is ready to be configured for testing on the Concourse build server.

**Comment by jsi** [comment]
Tested this with 6.12.2 and had 6 tests fail, which is correct, so this issue is verified.
