### ISSUE TITLE
HTML Area toolbar has incorrect location when text component is being edited

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#195]
1. Open a site wizard and select Features in apps
2. select the  Default controller
3. Open Page component View
4. insert a text component
BUG: toolbar has incorrect location
![toolbar](https://user-images.githubusercontent.com/3728712/32273172-6c36fffc-bf12-11e7-92a3-9fff387c1355.png)

**Comment by alansemenov** [comment]
Check 6.12 (where it's correct) and find out which new changes in 6.13 broke the toolbar
