### ISSUE TITLE
Error in the browser-console after a new component is added and descriptor is selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#20]
1. open site-wizard, select Features in apps, select Main Region in controller-dropdown
2. open the ComponentView and select 'insert Image' menu item 
3. select an image in the dropdown handler
BUG: error appears when the image has been selected
![image-comp](https://user-images.githubusercontent.com/3728712/30538145-496fc4e6-9c75-11e7-8955-865ab6a364ee.png)

The same issue when try to create a fragment from the existing text-component

**Comment by alansemenov** [comment]
Same error when selecting a descriptor for a layout or a part
