### ISSUE TITLE
Implement DuplicateContentDialog with progress bar

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#223]
* Should derive from ProgressBarDialog
* Unlike Publish content or Move content dialogs, this dialog will always have a progress bar
* The dialog should not open if there's no active duplicate content task and should close instantly when current active task is finished
* Localise all the texts

![image](https://user-images.githubusercontent.com/11612490/32542119-eedec8e0-c471-11e7-99a1-2d78f0f35e51.png)

**Comment by sigdestad** [comment]
Are we sure it should always have a progress bar? What if you are only copying a single node etc?

**Comment by alansemenov** [comment]
If we are copying a single node then the dialog itself won't be shown because the task will be finished before the threshold time. What I meant was that there will be nothing else in that dialog except for the progress bar (in other dialogs we have selectors etc.).
