### ISSUE TITLE
Implement tabbed panel in the Issue dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#232]
We will split issue details and item list in the existing issue's details dialog in two tabs: "Issue" and "Items". Later on we will add a third tab: "Comments". "Items" tab should also display current number of items inside the brackets (same number as on the "Publish" button).

* Implement tabbed panel
* Tabbed panel should be visible *only* for an existing issue
* Move content selector, item list and the "Publish" button to the second tab
* For a new issue there should be no tabs and content selector should still be visible right away (see #230)
* Show number of content items (same as what we show on the "Publish" button now) in the title of the "Items" tab (only if it's not 0): "Items (25)"

![image](https://user-images.githubusercontent.com/11612490/32555039-ed1f55cc-c49b-11e7-9e58-1bdcc8b61112.png)

![image](https://user-images.githubusercontent.com/11612490/32554722-026eb770-c49b-11e7-8908-54c9832fe295.png)

**Comment by pmi** [comment]
Pushed to an epic branch #237
