### ISSUE TITLE
Autosave issue on content items change

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#235]
Now we show content items in "readonly" mode and user must click Edit Issue button to be able to change the list. We will change that to always enable user to change the items list, so it will always be in the edit mode.

* Always show content selector and items underneath in edit mode
* Implement debounced auto-save of the issue, for example in 1 second after the last change of the list (make sure that save notification is still shown after auto-save)
* Change the number in the "Items" tab label whenever the number changes 

![image](https://user-images.githubusercontent.com/11612490/32554987-d681f770-c49b-11e7-84b9-b679cc6a7b1b.png)

**Comment by pmi** [comment]
Pushed to #237 branch
