### ISSUE TITLE
Console errors when creating a fragment from the layout

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#250]
1. start to add a site, open wizard
2. Select 'features', 'default' controller
3. Insert 3-column layout
4. Open the PageComponentView and select the layout
5. Select the Create fragment in the context menu
BUG:  
![layout](https://user-images.githubusercontent.com/3728712/32719490-9e6900ac-c871-11e7-908a-bd2e737ce98e.png)

`Failed to load resource: the
http://localhost:8080/admin/portal/edit/draft/573339df-7bfb-4805-a675-07efec039bab/_/component/main/1`
 
**Case 2:** do steps 1-4 and insert an image into the layout and create a fragment from the image

**Comment by alansemenov** [comment]
This bug is not in 6.12, so it might've been caused by moving the Editor out of admin-common.
