### ISSUE TITLE
SaveBeforeClose does not appear when changing order of occurrences

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#262]
1.  Open a HtmlArea content(0:2) and swap the areas.
2. Do not save the content and click on the 'Close' button on the tab.

Bug: 'Save Before Close' dialog should appear, because there are unsaved changes
 The same issue in ImageSelector-content - swap an images and close the wizard

**Comment by alansemenov** [comment]
Duplicate of https://github.com/enonic/xp-apps/issues/340
