### ISSUE TITLE
Fix layout in Image component descriptor

### ISSUE THREAD

**Issue by pmi** [enonic/xp-apps#266]
@alansemenov commented on [Wed Nov 15 2017](https://github.com/enonic/lib-admin-ui/issues/179)

![image](https://user-images.githubusercontent.com/11612490/32808746-7256bcce-c994-11e7-9435-952c11830c11.png)
![image](https://user-images.githubusercontent.com/11612490/32808771-87dca9dc-c994-11e7-8204-541914f014ba.png)

**Comment by alansemenov** [comment]
It's now correct in the Wizard form and Page Editor but still broken inside Inspect panel

![image](https://user-images.githubusercontent.com/11612490/32944777-f46f2aea-cb90-11e7-9a00-9d87abfe05f1.png)
