### ISSUE TITLE
Error appears when trying to save a site with Part or Layout-component and option is not selected 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#271]
1. Open Features and open the PageComponentView
2. Insert a part-component or layout-component
3. Do not select option in the selector
4. Press the Save button

Bug: error apears in the console and error-notification message appears

![part](https://user-images.githubusercontent.com/3728712/33021166-f038473a-ce11-11e7-8fe3-b7f9acf47598.png)

![notification](https://user-images.githubusercontent.com/3728712/33021226-258656f2-ce12-11e7-831c-80aadb238de7.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp #5818](https://github.com/enonic/xp/issues/5818) via [**ZenHub**](https://www.zenhub.com/)
