### ISSUE TITLE
New Content - Go directly to Wizard when there's only one content type available

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#274]
Very often there's only one content-type available in the New Content dialog in which case it becomes a redundant (and confusing) step that we should skip. Go directly to the Wizard in this case, skipping the dialog entirely.

![image](https://user-images.githubusercontent.com/11612490/33068384-65dca892-ceb1-11e7-9f04-b6f2914ac7b0.png)

**Comment by sigdestad** [comment]
Not sure where you got this task Alan - was it NAV? I'm worried about the consistency of our UI if we do this without thinking a bit more about things?

**Comment by alansemenov** [comment]
This was discussed several times before as a part of "New content" dialog not being easy to use dialog which popped up many times on discuss. I just made it as my own backlog to not forget it. Very irritating having to see this dialog every time when creating a new page template for example.

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #38](https://github.com/enonic/app-contentstudio/issues/38) via [**ZenHub**](https://www.zenhub.com/)
