### ISSUE TITLE
Different state of Preview button, when all items are selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#286]
Case 1
1. Expand a folder with images
2. Click on the site-row
3. click on the 'select all' checkbox. Result - all items are seleted and the Preview is **enabled**
The prview button is enabled
![prev1](https://user-images.githubusercontent.com/3728712/33077498-0ad54910-cee1-11e7-89b1-ba696c261bbf.png)

Case 2:
1. Expand a folder with images
2. click on the 'select all' checkbox. Result - all items are seleted and the Preview is **disabled**

![prev2](https://user-images.githubusercontent.com/3728712/33077656-574f5b5a-cee1-11e7-9879-48e65f84d438.png)

**Comment by sigdestad** [comment]
I think there is a hardcoded limit to how many items one can preview - so this is probably not a bug!

**Comment by sgauruseu** [comment]
But not clear notification appears here:
![mess](https://user-images.githubusercontent.com/3728712/33079371-76dd91e4-cee6-11e7-820e-80910f8113c8.png)
