### ISSUE TITLE
Prepare workshop on testing

### ISSUE THREAD

**Issue by jsi** [enonic/xp-apps#290]
We are planning a workshop for December 8th, 2017, on testing with JavaScript.  This is approximate schedule in Oslo-time:
09:00: Presentation by Siarhei
09:30 - 16:00: Group work, writing tests.

**Comment by sgauruseu** [comment]
1. Test for Greed Panel and Toolbar. 
     -install two applications and verify, that two rows with applications are present in the grid
     - Select an application and check state of all buttons.
     -Unselect the application and verify, that all buttons returned to the initial state
     -check the 'select all' checkbox and verify, that all applications are selected
     -uncheck the 'select all' checkbox and verify, that all applications are unselected.
2. Tests for ' Install' and 'Uninstall' modal dialogs and tests for installing and uninstalling an application.
3. Tests for Item Statistics Panel. 
     -Select a application and verify the app-info: Descriptors, Info, Schemas, Providers.  
        Stop the application and check the info on the statistic panel. Start application and  check it again.
     -Select two applications and verify the info.
  
4. Tests for the Grid-Context Menu . 
     -Verify that an application is stopped when the required menu item has been clicked. 
     -open the context menu on the stopped application and verify all menu-items.
     -select all applications and verify all menu-items    
     -Tests for  selections in the grid( Select All, Shift + Arrow Down, Shift  Arrow Up, click on  a row + 
       press white space keyboard).

**Comment by jsi** [comment]
The workshop has been postponed to Thursday, January 4th.
