### ISSUE TITLE
Role created with wrong permissions

### ISSUE THREAD

**Issue by aro** [enonic/xp-apps#333]
The roles created using Users app 6.12 are created with the wrong READ permissions in the role node. This is because it uses createNode api instead of the createRole function.

The node gets READ for "role:system.everyone".
While when using the proper api it gets READ for "role:system.authenticated"

The effect is that when a user that is updated with the role, is logging in, the role is not fetched and appears as if the user does not have the role.

[This issue was reported in Discuss.](https://discuss.enonic.com/t/admin-tool-permissions-unable-to-get-a-new-roles-to-work-with-tool/1331)

Note that this is fixed in master (6.13), the problem is for 6.12.

**Comment by alansemenov** [comment]
Cherry-picked commits from 6.13 into 6.12 branches

**Comment by sigdestad** [comment]
Hmm.. Just got afraid this might have happened to creation of users, userstores and groups too?
Can we verify thiat this is not the case?

**Comment by alansemenov** [comment]
Users and groups are fine - they are created with authLib in 6.12.
User stores are not done - we had to switch from GraphQL to REST before we released 6.12. We must fix this before we release 6.13 - there's an epic for this: https://github.com/enonic/xp/issues/5733
