### ISSUE TITLE
Launcher panel should not react to keyboard events when a modal dialog is active

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp-apps#36]
In 6.12 beta 1 (also in 6.11 and earlier) the order in which the ESC button closes things is wrong when you open any of the modals (two of them) on the home screen.

When first opening the home screen, ESC will close the tool menu.

If you keep that open, and instead open the XP Tour modal, or the About modal, then the ESC button will still close the tool menu first, and on the second press it will close the modal. This is backwards. The current modal should be closed first, then the admin tool menu can take over control of the ESC button again.

![screen shot 2017-09-21 at 10 10 27](https://user-images.githubusercontent.com/1465598/30685417-1f8b6a30-9eb5-11e7-999c-d0c5997ce2fb.png)

**Comment by Bellfalasch** [comment]
Not sure if this is in review, but using ESC will still close the launcher before modals in 6.12.2.

**Comment by alansemenov** [comment]
This is not merged yet, no
