### ISSUE TITLE
Refresh options in the Page Template selection when templates change

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#360]
1. Open Features
2. Open Inspection Panel 
3. Go to the grid and  delete the 'main region only' template
4. Go to the site-wizard

BUG: 
- the template still displayed in the panel
![main-r1](https://user-images.githubusercontent.com/3728712/33931364-d211e80a-e000-11e7-8551-772428f4548e.png)

Select the Automatic( main region only) in the  PageTemplateSelector

![main-r2](https://user-images.githubusercontent.com/3728712/33931470-25369dbe-e001-11e7-963d-4b9683232f03.png)

Error 404 appears in the console, when Save button has been pressed. And empty page is displayed in the PageEditor:

![result](https://user-images.githubusercontent.com/3728712/33931510-4ab0e25c-e001-11e7-95e2-82c1b0eea321.png)

**Comment by pmi** [comment]
Fixed by the #359
