### ISSUE TITLE
Add selenium tests to verify xp#5674

### ISSUE THREAD

**Issue by jsi** [enonic/xp-apps#368]
@sgauruseu commented on [Wed Oct 25 2017](https://github.com/enonic/xp-ui-testing/issues/87)

https://github.com/enonic/xp/issues/5674

Application controller not called for URL ending in /

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #9](https://github.com/enonic/app-contentstudio/issues/9) via [**ZenHub**](https://www.zenhub.com/)
