### ISSUE TITLE
Buttons in the grid toolbar are still enabled after content is deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#398]
Case 1:
1. Select 2 folders in the root directory
2. Press Delete button on the toolbar
3. Type a number and confirm deleting
BUG: when modal dialog is closed, buttons  Delete, Move, Publish, Preview are enabled

![grid](https://user-images.githubusercontent.com/3728712/34247038-268fbc58-e642-11e7-81ef-3d31fdd15684.png)

Case 2:
1. Add a parent folder
2. Add a child to the parent
3. type the parent's name in the filter panel
4. Click the checkbox 
5. Press Delete on the toolbar
6. Confirm deleteing
Bug - buttons has incorrect state

**Comment by alansemenov** [comment]
@edloidas what is the status of this one?
