### ISSUE TITLE
HTML Area - Textbox in the Source Code dialog overflows the modal dialog 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#400]
1. Open a site in Edge and insert a text component
2. Click on the Source Button

Issue:
![source-code](https://user-images.githubusercontent.com/3728712/34251764-2e49043a-e652-11e7-91f2-0478cbbe09ea.png)

**Comment by sgauruseu** [comment]
I just reproduced the issue on Chrome(latest build) +Windows

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #282](https://github.com/enonic/lib-admin-ui/issues/282) via [**ZenHub**](https://www.zenhub.com/)
