### ISSUE TITLE
Template selector - List templates in the same order as in the grid

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#402]
Seems like we always sort alphabetically now, but in the case below it's confusing why the second template is shown as default. We should list the templates in the same order as in the grid since that's the order we use to determine the default (first) template. 

![image](https://user-images.githubusercontent.com/11612490/34252927-ce497d3c-e645-11e7-942b-85b75bb0d72e.png)

**Comment by pmi** [comment]
Pushed the fix to lib-admin-ui#269
