### ISSUE TITLE
Time, DateTime contents - incorrect validation in wizard, when white space typed in the input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#404]
1. Open  wizard for Time content
2. Type the time (keyboard) 14:00 and add a white space in the end.

BUG: red border appears in the input, when  the  white space  has been typed

![time-content](https://user-images.githubusercontent.com/3728712/34258281-47cca7ba-e66e-11e7-9437-36ebdda83755.png)

It should work in the same way as, for example, for Long content. When we enter space before or after the number, the field will still be valid.

![image](https://user-images.githubusercontent.com/11612490/34300840-52675244-e72a-11e7-8023-45af871f426f.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #286](https://github.com/enonic/lib-admin-ui/issues/286) via [**ZenHub**](https://www.zenhub.com/)
