### ISSUE TITLE
Issue List dialog - After an issue was closed it remains visible under 'Open Issues'

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#418]
Clear the 'repo' and 'work' folders and start the server again
1. Click on folder and create an issue
2. Do not close the Issue-Dialog and click on Items-tab
3. Press the 'Publish and Close' button
Bug: when the issue has been published, list of opened issues is opened and the issue still present here.

<img width="632" alt="iss1" src="https://user-images.githubusercontent.com/3728712/34341535-5685b5f0-e9aa-11e7-923a-43f982cbe1c8.png">

<img width="698" alt="iss2" src="https://user-images.githubusercontent.com/3728712/34341539-5ee7bd92-e9aa-11e7-8355-aa0ae19d9c9e.png">

**Comment by pmi** [comment]
@sgauruseu Please check if this is still actual.
Firstly there's no 'Publish' button.
Secondly, after I create an issue and press 'Publish & Close Issue' button the dialog is closed and the issue list is reloaded with the newly created issue being closed.

**Comment by sgauruseu** [comment]
I mean the "Publish and Close", when press it the issue has been closed, but the issue is present in the both
tabs, see on screenshots: 'Test Issue 1' is opened and closed at the same time
