### ISSUE TITLE
Double Content - 'Red Circle' is not displayed in the grid, when default value is more then max value

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#424]
1. Double content type has the next configurations elements:(input is required)
` <default>3.5</default>  <occurrences minimum="1" maximum="0"/>`

   and:
`<config>
      <min>0</min>
      <max>3.14159</max>
      </config>`
2. Open the wizard

<img width="820" alt="issue1" src="https://user-images.githubusercontent.com/3728712/34386077-f2275598-eb37-11e7-9d41-5c7901b78e31.png">

**Issue** :
Value is not valid, but 'red icon' is not present in  the grid-panel, but it present in the wizard only.
So we can publish the content in the grid.
**Should we check the default value, when the MAX value is configured?**

<img width="888" alt="double1" src="https://user-images.githubusercontent.com/3728712/34405683-a5c44f6a-ebc5-11e7-8f08-fdaac29c58c0.png">

**What value was published?**  Is this content published with not valid value?

**Comment by alansemenov** [comment]
This should be solved when https://github.com/enonic/xp-apps/issues/425 is fixed. After default value is invalidated, the red circle will appear automatically.
