### ISSUE TITLE
TextLine(TextArea) content (0:0) - clicking on the button Add does not add new Input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#427]
This issue does not reproduce with Double content
1) Add the config to the textline(0:0):

`<config> `
` <max-length>11</max-length>`
`</config> `

2. Open a wizard for the textline
3. Click on Add buton
Bug: the button has been pressed, but new input not added

<img width="916" alt="textline9" src="https://user-images.githubusercontent.com/3728712/34406769-c36225aa-ebcb-11e7-8cdd-a04fb900303b.png">

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #281](https://github.com/enonic/lib-admin-ui/issues/281) via [**ZenHub**](https://www.zenhub.com/)
