### ISSUE TITLE
Error when trying to save as page template from a non-site content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#453]
1. Click on the Features and select Checkbox content, for example
2. type a name and select the 'Main Region' in the controller-options
3. Open the 'Inspection Panel' and press the 'Save as template' button.

Exception occurs: 
`Caused by: com.enonic.xp.content.ContentNotFoundException: Content with path [/features/r3e/_templates] was not found in branch [draft]
        at com.enonic.xp.core.impl.content.GetContentByPathCommand.execute(GetContentByPathCommand.java:32)
        at com.enonic.xp.core.impl.content.CreateContentCommand.validateCreatePageTemplate(CreateContentCommand.java:194`

<img width="949" alt="checkbox" src="https://user-images.githubusercontent.com/3728712/34721006-0d08c486-f552-11e7-8a39-12e96a644fd1.png">

**Comment by alansemenov** [comment]
When saving a template, we should first find the closest site of the content and then find its "templates" folder. 

If content doesn't have the ancestor site, the "Save as Template" action should be hidden.
