### ISSUE TITLE
Details Panel- when content is not valid, icon overlaps the display name

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#454]
1. Add a page-template without a selected support.
2. Select the template and open the details panel

Bug: red icon overlaps the display name
<img width="217" alt="details" src="https://user-images.githubusercontent.com/3728712/34765144-c7876538-f601-11e7-904f-baa2a724b6fc.png">

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #357](https://github.com/enonic/lib-admin-ui/issues/357) via [**ZenHub**](https://www.zenhub.com/)
