### ISSUE TITLE
Users App - GraphQL - Auth config GraphQL types

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp-apps#460]
Today we JSON.stringify and JSON.parse the authConfig.
But the format of the authConfig is actually fixed.

- [ ] Create the missing GraphQL types (Base the names on the equivalent Java classes). 
- [ ] Adapt the GraphQL schema
- [ ] Adapt the client side (TS requests)

- [ ] Do the same for inputs

**Comment by GlennRicaud** [comment]
Needs some modifications in GraphQL lib. On hold until it is done.
Not necessary for the epic so will be removed from it

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-users #73](https://github.com/enonic/app-users/issues/73) via [**ZenHub**](https://www.zenhub.com/)
