### ISSUE TITLE
Red Icon does not present when  a template was duplicated by clicking on 'Save as Template'   menu item

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#470]
1. Select and open the  'Main region only'  page template, open the PageComponentView
2. Click on the 'Save as template ' menu item 
<img width="613" alt="f-main" src="https://user-images.githubusercontent.com/3728712/34869775-10aa85a4-f799-11e7-8125-6f2a3c1bbe99.png">

3. Go to the grid and look at the copy of the template, red-icon is not displayed
4. Open the copy, 
Bug: red icon is present in the template-wizard, because the 'supports' option is not selected (OK)
Expected: red icon should be displayed in the grid as well

<img width="743" alt="templ-2" src="https://user-images.githubusercontent.com/3728712/34869928-9d54b9fc-f799-11e7-9e94-abc5b5e355fe.png">

**Comment by alansemenov** [comment]
Would probably be obsolete after https://github.com/enonic/xp-apps/issues/500 is done

**Comment by alansemenov** [comment]
We no longer allow "Save as Template" action from inside the template wizard, so this is obsolete.
