### ISSUE TITLE
Issue Details dialog - Dependent items are not removed after all items are unselected in the content selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#487]
1. Select a folder with 10 contents, for example and create new issue.( do not include child)
2. click on the 'Publishing Issues' and open the issue
3. click on the 'Include child' link
 Items with 11 items appears:
<img width="729" alt="step1" src="https://user-images.githubusercontent.com/3728712/35148015-b546f862-fd21-11e7-83a9-65d8299b567f.png">

4. Open the drop-down options and uncheck the parent folder and press Apply button
BUG: number of Items is not updated and  not clearly is the issue has been updated.

<img width="604" alt="iss0" src="https://user-images.githubusercontent.com/3728712/35148113-1ccd4f40-fd22-11e7-8eb0-428d96fb941e.png">

**Comment by alansemenov** [comment]
@pmi check if this is still valid after the latest changes
