### ISSUE TITLE
Selected image is not displayed on the ContentItemPreviewPanel 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#504]
1. Select a image in the grid
BUG :  440 error appears in the console and the image is not displayed

<img width="922" alt="grid" src="https://user-images.githubusercontent.com/3728712/35386043-8e760624-01db-11e8-8551-fe8e2a230d31.png">

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #315](https://github.com/enonic/lib-admin-ui/issues/315) via [**ZenHub**](https://www.zenhub.com/)
