### ISSUE TITLE
Enable detachment of components from a fragment

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#511]
1. Add a new action "Detach Fragment" to the context menu of a fragment component (remember to localise it). It should be available in Page Components view's context menu as well.
2. When the action is triggered, the fragment should be replaced with its components.
3. Refresh the page structure in the Page Editor and the Page Components view
4. Automatically select the main component of the original fragment on the page

**Comment by sigdestad** [comment]
Hmm.. How about using the workd "Explode Fragment" instead?

**Comment by alansemenov** [comment]
I don't see how this fits...

![image](https://user-images.githubusercontent.com/11612490/35510812-e61d555a-04f9-11e8-8efa-4d4ec21ecbb2.png)

**Comment by sigdestad** [comment]
Have you heard about "expoded views" Microfilm style. Alternatively, we could use the same as we do for pages based on templates. I.e. "Customize"? It is essentially the same thing that happens I guess!

**Comment by alansemenov** [comment]
I like "Customize"! But we should somehow make it obvious that this action is not going to affect the original fragment (which user would logically think if he chooses to customize a fragment).

**Comment by sigdestad** [comment]
Conceptually, the same thing happens for pages as for fragments, I think we should attempt using the same "jargon" for both pages and fragments. 

However, I just came up with an idea to make things more logical :-)

By adding an "Edit Page Template", and "Edit Fragment" directly from the menu, the user immediately gets a context. Then we can simply add the following actions for changing the items locally:

"Detatch from Template"
"Detach from Fragment"

Solved?

BTW: We should probably also consider the "Create Fragment" vs "Save as Page Template"..

**Comment by alansemenov** [comment]
Cool, this way it's obvious that the original fragment/template won't be affected. The only downside is that it's crazy long and I'm sure that we'll face some issues localising it. But that's semantics.

And yes, we should definitely change "Create Fragment" to "Save as Fragment".
