### ISSUE TITLE
Spinner should be displayed above the 'Edit Issue Dialog' when issue is updating 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#514]
1. Open an IssueDetailsDialog and click on the Edit Issue, Edit Issue Dialog is opened
2. Remove one of the items, press the `Save` button. IssueDetailsDialog is loading
3. Press the Edit Issue quickly.

Bug: item to publish,  that  was removed , is still present in the Edit Issue Dialog. 
Expected: Spinner should displayed above the 'Edit Issue Dialog' when issue is updating

![edit-issue](https://user-images.githubusercontent.com/3728712/35509475-4ada07d0-0505-11e8-83bb-6fb99a689832.png)

**Comment by sigdestad** [comment]
Our goal is to remove this "edit issue" view before we release 6.14. So hopefully we don't need to fix this issue! Don't spend time testing it either
