### ISSUE TITLE
Site Wizard - the color of selected application-view is not updated, when switch between versions and site configurator in an application contains required fields

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#520]
Case 1:
1. Open the site wizard and start to add new site.
2. Type a name and select 'Google Analytics App'
3. The red icon appears in the wizard, because the required field is not filled in the site-configurator. 
   And the selected option view is red(OK)
![step1](https://user-images.githubusercontent.com/3728712/35562947-61cac118-05b5-11e8-9afc-e4593ca45691.png)

4. Click on the `Edit ` icon and open the site-configurator, type a required data and press the `Apply`
 The site is getting valid and the selected option is not red now
5. Do not close the site-wizard and go to the grid, open the Version History panel and restore the previous version 

6. Go to the wizard again, 
Expected: selected  application should be red
Actual: option is not red, but the required input is empty
![result](https://user-images.githubusercontent.com/3728712/35563673-c95aef7c-05b7-11e8-8db7-7926957adb65.png)

Case 2:
1. Open the site wizard and start to add new site.
2. Type a name and select an application. Save the site(Do not close the wizard)
3. Add 2 applications in the site wizard and save the site again(Do not close the wizard)
4. Go to the Version History panel and switch to the previous version
5. Go to the wizard again
Bug : expected - one selected application should be in the wizard
Actual - tree applications still present in the wizard

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #374](https://github.com/enonic/lib-admin-ui/issues/374) via [**ZenHub**](https://www.zenhub.com/)
