### ISSUE TITLE
Incorrect state of Save button when an image is opened for the first time

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#524]
This bug can be linked with the  [https://github.com/enonic/lib-admin-ui/issues/315](url)
1. Upload an image
2. Open the image in the wizard
Bug - when the image is opened, `Save` button is getting visible, but no any changes were applied
Click on the Save button, close the wizard and open the image again. Saved button is visible

![img_wiz](https://user-images.githubusercontent.com/3728712/35618730-1c779a10-067c-11e8-8c40-b56f4ffa18f7.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #322](https://github.com/enonic/lib-admin-ui/issues/322) via [**ZenHub**](https://www.zenhub.com/)
