### ISSUE TITLE
Refactor CreateUserStoreRequest and UpdateUserStoreRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#542]
These two classes are identical except for the mutation name. We should use one class (call it ``SaveUserStoreRequest``) and pass mutation name to the constructor.

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-users #74](https://github.com/enonic/app-users/issues/74) via [**ZenHub**](https://www.zenhub.com/)
