### ISSUE TITLE
Template wizard - 'Edit' icon should not be displayed in support selected options

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#557]
1. Open a template wizard and select any options in the supports
Bug: Edit icon should not be displayed in the selected options 
![edit](https://user-images.githubusercontent.com/3728712/35965973-c8f2b66c-0cbc-11e8-9a4d-8a63138701aa.png)

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/336
