### ISSUE TITLE
HtmlArea, InsertImage dialog - error in the console, when dialog has been opened

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#56]
1. open HtmlArea-content
2. click on the InsertImage button
BUG see the screenshot
![arrow](https://user-images.githubusercontent.com/3728712/30805931-5e18179a-a1fc-11e7-9fe6-45e130d7fb6f.png)

**Comment by alansemenov** [comment]
Moved into https://github.com/enonic/xp-apps/issues/46
