### ISSUE TITLE
UserStore wizard - incorrect validation styling when ID provider with required inputs has been selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#581]
1. Start to add a new User Store
2. Type a name and select  a provider with required inputs( install the application, before : Auth0 ID Provider)

Issue: Not clear message appears, when the provider is selected
<img width="666" alt="store1" src="https://user-images.githubusercontent.com/3728712/36256716-1fdae8a2-1265-11e8-9533-e3ee342b83ce.png">

Click on edit icon and type the inputs. Store is getting valid
<img width="686" alt="provider" src="https://user-images.githubusercontent.com/3728712/36256867-c6d88aec-1265-11e8-98ad-69ec50ca9b2f.png">

**Comment by alansemenov** [comment]
There should be no message at all (and not two-coloured validation either). It should look exactly the same as in the Site config:

![image](https://user-images.githubusercontent.com/11612490/36257228-48b9caf4-1256-11e8-9444-bb59e73641ea.png)

**Comment by pmi** [comment]
Seems it works as expected already
![capture](https://user-images.githubusercontent.com/754221/38768254-5d0fc37a-3ff9-11e8-895f-bc87ddc85a09.PNG)
