### ISSUE TITLE
Icon remove is not displayed when options in  Combobox have been selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#590]
1. Click on Features and select 'Combo box' type
2. Select any options in the wizard
BUG: Icon 'remove' should be present when options are selected

<img width="668" alt="comb" src="https://user-images.githubusercontent.com/3728712/36304207-d27517f2-131f-11e8-8e42-778c2001b4f9.png">

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #342](https://github.com/enonic/lib-admin-ui/issues/342) via [**ZenHub**](https://www.zenhub.com/)
