### ISSUE TITLE
Applications - show intermediate status for long application startup time

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#614]
1. Put Features app into the deploy folder
2. Go to content-grid and delete  Features site and Large tree
3. go to  Applications and stop Features
4. start Features again

**Issue**: when 'Start' button  has been pressed, applications is starting, contents are importing and status is 'Stopped'.  Status changed to 'Started' in 7 seconds, when all content are imported .
 
**Expected**: progress bar should be displayed, when the applications is starting

**Comment by alansemenov** [comment]
@sig I don't think this is possible. Progress bar can be displayed when we can calculate current progress related to the total, for example when we know how long the entire operation will take or how many items should be processed by the operation. In this case we don't know that. What we could do is show some intermediate status, like "Initializing..." between "Stopped" and "Started".

**Comment by sigdestad** [comment]
Could we at least show a "starting" icon or animation rather than a progress bar then?

**Comment by alansemenov** [comment]
We could replace status with a spinner during initialization

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-applications #10](https://github.com/enonic/app-applications/issues/10) via [**ZenHub**](https://www.zenhub.com/)
