### ISSUE TITLE
Translate admin tools descriptions to French

### ISSUE THREAD

**Issue by aro** [enonic/xp-apps#634]
Translate the texts from the admin tool xml descriptors for Applications, Users, Content Studio apps.

There are 2 keys that can be translated: 
- admin.tool.displayName
- admin.tool.description

Add the translations to the phrases file in i18n directories:

`modules/app-contentstudio/src/main/resources/i18n/phrases_fr.properties`
`modules/app-users/src/main/resources/i18n/phrases_fr.properties`
`modules/app-applications/src/main/resources/i18n/phrases_fr.properties`

**Comment by GlennRicaud** [comment]
Also from jsi using the diff tool:

*Applications App:*
The following keys are missing in ‘phrases_fr.properties’: [admin.tool.displayName, admin.tool.description]
*Content Studio App:*
The following keys are missing in ‘phrases_fr.properties’: [live.view.saveAs.fragment, action.saving, action.commentIssue, live.view.detach, action.saved, field.comments, notify.issue.commentUpdated, notify.component.detached, notify.issue.commentDeleted, notify.repo.readonly, notify.issue.commentAdded, admin.tool.displayName, dialog.issue.confirmCommentDelete, field.issue.noComments, admin.tool.description]
*Standard ID Provider App:*
The following keys are missing in ‘phrases_fr.properties’: [page.creation.password.short]
*Users App:*
The following keys are missing in ‘phrases_fr.properties’: [admin.tool.displayName, admin.tool.description]
