### ISSUE TITLE
Display the list of application's widgets in Application Info panel

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#655]
Fetch the list of widgets from selected application and show the list of display names sorted alphabetically. Show widget key as a tooltip on hover. Show widget interface in brackets after display name.

![image](https://user-images.githubusercontent.com/11612490/36840825-abebb4de-1d46-11e8-8ed8-09ac176fc10b.png)

**Comment by sigdestad** [comment]
Cool. Could we also list what implementation the widget has?
‌‌
Vennlig hilsen/Best regards
Enonic AS

Thomas Sigdestad
CTO
+47 98236011

https://enonic.com <https://enonic.com/> - Your idea, one platform, any cloud

**Comment by alansemenov** [comment]
What is implementation of a widget?

**Comment by sigdestad** [comment]
Widgets must specify an interface (com.enonic.content-studio.context-panel etc)
