### ISSUE TITLE
Widget content is duplicated inside the Detail panel [Firefox]

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#671]
![image](https://user-images.githubusercontent.com/11612490/37024097-3e1bb054-2128-11e8-96cf-1817dda8921d.png)

**Comment by alansemenov** [comment]
This is caused by HTML Imports polyfill, that's why it can only be reproduced in Firefox. The latest version of the polyfill solves that, but they changed so much since the version that we are using (ours is 3 years old) that we will have to change our widgets template.

I'm putting this on hold for now, until I find a better solution. 

Solution to this specific problem with the Data Toolbox widget is to verify if the container is empty before appending contents or clearing it every time before appending.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #390](https://github.com/enonic/lib-admin-ui/issues/390) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #36](https://github.com/enonic/app-contentstudio/issues/36) via [**ZenHub**](https://www.zenhub.com/)
