### ISSUE TITLE
IssueDeatilsDialog - IncludeChildrenToggler is getting not clickable when the issue has been closed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#672]
1. Select Features and click on Create Issue
2. Type a title and save it 
3.  Navigate to Items tab and  select 'Close' in IssueStatusSelector

Bug: icon 'IncludeChildrenToggler  ' is getting not clickable when the issue has been closed

<img width="706" alt="features" src="https://user-images.githubusercontent.com/3728712/37024676-94f93a4c-213a-11e8-8544-52e6b83166bf.png">

**Comment by sigdestad** [comment]
Are you saying it is a bug that you cannot toggle tree icon after issue is closed?
Actually, the bug in this case is that you are allowed to close an issue with 1 or more items still attached to it...

**Comment by sigdestad** [comment]
Lets discuss this before we make any changes...

**Comment by pmi** [comment]
@alansemenov @sigdestad Any resolution on this ?

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #30](https://github.com/enonic/app-contentstudio/issues/30) via [**ZenHub**](https://www.zenhub.com/)
