### ISSUE TITLE
IssueDetailsDialog - invalid content should be reloaded in the dependent-list, when the content has been edited 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#674]
1. Create a folder with children and at least one should be not valid (shortcut for example)
2. Select the folder and create issue.
3. Select the issue and open Issue Details Dialog, click on **Include Child** icon

<img width="589" alt="step1" src="https://user-images.githubusercontent.com/3728712/37036332-62f0663a-2160-11e8-9803-f435aff63db4.png">

4. Click on the '**Edit invalid content**', (content is opened) and specify a target . Shortcut is getting  valid, save it.
5. Navigate to the tab with IssueDetails

Bug: The dependent content still is invalid on the dialog

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #60](https://github.com/enonic/app-contentstudio/issues/60) via [**ZenHub**](https://www.zenhub.com/)
