### ISSUE TITLE
Template Wizard - Inspection Panel should appear after page controller is selected 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#686]
1. Expand a site(with application) and open template-wizard
2. Type a name and select a page controller

Bug: ContextWindow  should be opened automatically, when page-controller has been selected 
(See the correct behavior when page controller is selected in a site-wizard)

<img width="902" alt="templ2" src="https://user-images.githubusercontent.com/3728712/37288961-99f7500e-2619-11e8-917d-262af59d7443.png">

**Comment by alansemenov** [comment]
Case 2 is a duplicate of https://github.com/enonic/xp-apps/issues/714 so I'm removing it from here

**Comment by sgauruseu** [comment]
New ui-tests added.
