### ISSUE TITLE
SiteWizard - red icon should be displayed  in the wizard, when required inputs in site-configurator are not filled

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#688]
Case 1:
1. Install  'Google Analytics App'
2. Go to CS and  start to add new site, open site-wizard
3. Type a name and select 'Google Analytics App' in apps
4. Click on 'save', 

Bug:  Red icon should be present in the wizard, because site-configurator contains required input
But red icon is displayed in the browse panel

<img width="657" alt="wizard" src="https://user-images.githubusercontent.com/3728712/37340400-0c82cd8c-26cf-11e8-84e7-68996a76baaa.png">

Case 2:
1) Install an application with meta-data(mixin)
2) Open site-wizard, select the application, type a name, (do not fill required inputs in metadata step), save

BUG: required input is red, but the site is valid in the wizard-page(red icon is not displayed)

**Comment by alansemenov** [comment]
Fixed in another issue
