### ISSUE TITLE
iPhone and iPad specific bug - scrolling is not working in content wizard, when cursor over an input field

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#699]
1. Open a scrollable content in iPhone

Issue: problems with scrolling of content when the content  has several inputs

**Comment by runarmyklebust** [comment]
To be specific; when touching an input-field, the scrolling is not scrolling, but just bouncing the screen.

**Comment by runarmyklebust** [comment]
2) Try to scroll when touching an input-field. 

A large html-area or text-area makes scrolling very difficult since most of the screen is an input field then.

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #26](https://github.com/enonic/app-contentstudio/issues/26) via [**ZenHub**](https://www.zenhub.com/)
