### ISSUE TITLE
Site wizard - application-view  is not correctly updated in few cases

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#700]
1. Create a site,- type a name and save it
2. Create one more version of the site: select  an application, save the site
3. Click on  'Log out'.
4. Login again and open the site. Do not close the wizard, go to browse panel
5. Open the Version history and restore the version of site without an application
6. Go to site-wizard, 
Expected: the application should not be present on the application view
Actual: application is present

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #424](https://github.com/enonic/lib-admin-ui/issues/424) via [**ZenHub**](https://www.zenhub.com/)
