### ISSUE TITLE
Show a tooltip with content type key in the Search Filter 

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#703]
![image](https://user-images.githubusercontent.com/11612490/37659167-8b986d54-2c4f-11e8-8608-2a6dff505ac2.png)

https://enonic.zendesk.com/agent/tickets/2377

**Comment by sgauruseu** [comment]
Issue moved to [enonic/app-contentstudio #39](https://github.com/enonic/app-contentstudio/issues/39) via [**ZenHub**](https://www.zenhub.com/)
