### ISSUE TITLE
User Store Wizard - 404 error when try to select ID provider 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#710]
1. Open user  store wizard, type display name
2. try to select ID Provider: type a name in the options filter or expand options in the dropdown
Error in browser console, 

`Service error: Could not find resource for full path: http://localhost:8080/admin/rest/application/getIdProviderApplications`

![err_id_provider](https://user-images.githubusercontent.com/3728712/37968119-fa4f57d6-31d5-11e8-8caa-e86ff14ded8e.png)

**Comment by alansemenov** [comment]
@sgauruseu I cannot reproduce this - both search and dropdown work fine
