### ISSUE TITLE
Icons are not displayed in `HtmlArea` on the mce-toolbar

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#717]
1. Build for production:
```
gradle flush -Penv=prod
gradle deploy -Penv=prod
```

**Bug:**
Open HtmlArea content - icons are not displayed on the mce-toolbar

**Comment by edloidas** [comment]
Already fixed in `master`.

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #426](https://github.com/enonic/lib-admin-ui/issues/426) via [**ZenHub**](https://www.zenhub.com/)
