### ISSUE TITLE
Group and roles are placed incoherently in Users

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#741]
@diegopasten commented on [Tue Mar 20 2018](https://github.com/enonic/xp/issues/6127)

When looking at a user in the users tools Roles is to the left (or first) and groups is to the right (second), but when in user creation window its opposite Groups on top (first) and Roles below (second). 

Seems like a small thing but since I can't duplicate a user this is a bit annoying, when "copying" a user.

**Comment by alansemenov** [comment]
Switch places Groups and Roles in the user wizard so that Roles is on top.

**Comment by pmi** [comment]
Issue moved to [enonic/app-users #70](https://github.com/enonic/app-users/issues/70) via [**ZenHub**](https://www.zenhub.com/)
