### ISSUE TITLE
ContentWizard - 404 error  appears , when a content with controller has been moved out of a site

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#756]
**Issue 1 - Incorrect behavior in WizardPage** 

1. Select Features and open Article-wizard, type a name and select 'main region' controller
2. Do not close the article wizard, move the article out of the site
3. Go to article-wizard
 **Actual**:  404 Site for content [/article] not found 

<img width="923" alt="article" src="https://user-images.githubusercontent.com/3728712/38503326-6f9f629e-3c1a-11e8-8818-5d8ed7965e17.png">

Refresh the page, PageEditor is getting not visible.

So,  **Expected behavior** : PageEditor should be hidden for the article content

<img width="936" alt="article-moved" src="https://user-images.githubusercontent.com/3728712/38503354-846e36be-3c1a-11e8-97e6-b4497f5c8baa.png">

**Issue 2 - Incorrect info in the Details Panel**
Page Editor is not displayed, but  controller 'main region' is present on the Details Panel.
Should the info on Details Panel be updated in this case? 
Should be "Page Template is not used" shown be here?

<img width="770" alt="det" src="https://user-images.githubusercontent.com/3728712/38504039-530a3ecc-3c1c-11e8-943d-4017e9daf6cb.png">

**Comment by alansemenov** [comment]
This bug is already registered here: https://github.com/enonic/xp-apps/issues/509 and we decided to not prioritise it. Will be fixed at some point.
