### ISSUE TITLE
Page Component View is not scrollable when page is locked

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#762]
1. Open `Super Hero` site (Chrome browser)
2. Click  on `Show Component View`

Bug:  View is not scrollable, need to click on `Customize` menu item. View is scrollable in FF

![comp](https://user-images.githubusercontent.com/3728712/38676229-092b471c-3e63-11e8-9622-dd5bddd2b4dd.png)

**Comment by alansemenov** [comment]
Seems like it only affects Chrome

**Comment by edloidas** [comment]
Issue moved to [enonic/app-contentstudio #13](https://github.com/enonic/app-contentstudio/issues/13) via [**ZenHub**](https://www.zenhub.com/)
