### ISSUE TITLE
Incorrect message appears when try to create a role with name that already in use

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#93]
1. Add a role 'test-role1'
2. Open role-wizard and type the same name : test-role1
Bug: see the message on the screenshot

![role](https://user-images.githubusercontent.com/3728712/31007988-20634f7a-a50b-11e7-9be5-d971708a9cf0.png)

**Comment by alansemenov** [comment]
That's how it's going to be for now. We will implement error message parsing and localisation in a separate task in 6.13.

**Comment by alansemenov** [comment]
This is correct now

![image](https://user-images.githubusercontent.com/11612490/33760306-7f6cc4f2-dc05-11e7-8bc1-1b7be59c164e.png)
