### ISSUE TITLE
Shortcut content - error when switching between versions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#94]
1. Open shortcut wizard, type a name and save it.
2. Select a target, Features, for example, do not close the wizard.( create some several versions of the content- set another target).
3. change target - select server.bat ( from distro). Save
4. change target - select an Image 
5.  change target - select an TXT 
6. Go to version history panel and restore the version without the target. Restore the version where
  target is SERVER.BAT

Bug: error appears in the console  and target restored does not always
```
TypeError: Cannot read property 'update' of undefined
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1506670896/js/bundle.js:7097:37
From previous event:
    at updateHandler (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1506670896/js/bundle.js:7096:93)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1506670896/js/bundle.js:7122:21
    at Array.forEach (<anonymous>)
    at contentUpdatedHandler (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1506670896/js/bundle.js:7121:22)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1506670896/admin/common/js/_all.js:54829:25
```

**Comment by alansemenov** [comment]
@pmi Apparently this can still be reproduced, please check.

**Comment by pmi** [comment]
Could not reproduce using the description above.
@sgauruseu could you write exact steps to reproduce it ?
