### ISSUE TITLE
Insert Link dialog - Switch places Content and URL tabs

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#98]
![image](https://user-images.githubusercontent.com/11612490/31021122-337a65ba-a535-11e7-9681-801625a9929c.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #87](https://github.com/enonic/lib-admin-ui/issues/87) via [**ZenHub**](https://www.zenhub.com/)
